### ISSUE TITLE
Frage 4 - Exam 2015

### ISSUE THREAD

**Issue by thomaseizinger** [thomaseizinger/cga-example-exams-answers#3]
Ich habs im [PR](https://github.com/thomaseizinger/cga-example-exams-answers/pull/2#commitcomment-15678103) von @sladiri schon angesprochen. Es geht um den folgenden commit e3cf32f729de1de518f270748ff2e35c836328a4.

Natürlich könnte man das mit einer Rigid-Body Simulation lösen, allerdings wäre das doch ein extremer Zeitaufwand. Was spricht dagegen, das mit einer physikalischen Simulation zu animieren?

**Comment by sladiri** [comment]
Ich meinte mit Rigid Body die einfachste physikalische Simulation, im Gegensatz zu Softbody, also ich glaube, das gleiche wie " physikalischen Simulation". Ich wollte das verdeutlichen, oder ist die Bezeichnung falsch?

**Comment by thomaseizinger** [comment]
Ich hatte nicht bedacht, dass ja jede Rigid Body Simulation eine physikalische Simulation ist, daher passt das schon :)
